/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  "/admin/deliveries": {
    /**
     * Get all deliveries
     * @description Retrieve a list of all deliveries
     */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Delivery"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/deliveries/{id}": {
    /**
     * Get delivery by ID
     * @description Retrieve a specific delivery by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Delivery ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["DeliveryOverview"];
            };
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/deliveries/{id}/stats/{format}": {
    /**
     * Get delivery statistics in CSV format
     * @description Retrieve delivery order statistics filtered by status and export as CSV
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter orders by status */
          status?: "PENDING" | "PAYMENT_IN_PROGRESS" | "PAYMENT_FAILED" | "PAID" | "RESOLVING" | "CONCILIATION_PAYMENT_IN_PROGRESS" | "CONCILIATED" | "CANCELED";
        };
        path: {
          /** @description Delivery ID */
          id: string;
          /** @description Output format */
          format: "CSV";
        };
      };
      responses: {
        /** @description Successful response with CSV file */
        200: {
          headers: {
            /** @description Attachment filename */
            "Content-Disposition"?: string;
          };
          content: {
            "text/csv": string;
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}": {
    /**
     * Get order overview by ID
     * @description Retrieve a specific delivery by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderOverview"];
            };
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /**
     * Update an order
     * @description Update an order's name
     */
    patch: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["OrderPatch"];
        };
      };
      responses: {
        /** @description Order successfully updated */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Order"];
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/order-pickings/{id}": {
    /**
     * Update order picking items
     * @description Update the items in an order picking
     */
    patch: {
      parameters: {
        path: {
          /** @description Order Picking ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["OrderPickingPatch"];
        };
      };
      responses: {
        /** @description Order picking successfully updated */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderPicking"];
            };
          };
        };
        /** @description Order picking not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/order-pickings/{pickingId}/items/{itemId}/collect": {
    /**
     * Collect an item in an order picking
     * @description Mark an item in an order picking as collected.
     */
    post: {
      parameters: {
        path: {
          /** @description Order Picking ID */
          pickingId: string;
          /** @description Item ID */
          itemId: string;
        };
      };
      responses: {
        /** @description Item successfully collected */
        204: {
          content: never;
        };
        /** @description Order picking or item not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}/order-picking": {
    /**
     * Start order picking process
     * @description Check if order picking exists, return existing one or create new from order
     */
    post: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Order picking found or created successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderPicking"];
            };
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}/consolidate": {
    /**
     * Resolve an order
     * @description Marks an order as resolved.
     */
    post: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Order successfully resolved */
        204: {
          content: never;
        };
      };
    };
  };
  "/admin/orders/{id}/cancel": {
    /**
     * Cancel an order
     * @description Cancel an order and emit OrderCancelledEvent. Order can only be cancelled if status is PENDING, PAYMENT_IN_PROGRESS, PAYMENT_FAILED, or PAID.
     */
    put: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Order successfully cancelled */
        204: {
          content: never;
        };
        /** @description Bad request (e.g., order cannot be cancelled in current status) */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}/conciliation": {
    /**
     * Get conciliation order
     * @description Retrieve the conciliation order for a given order ID
     */
    get: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Order"];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{orderId}/payments": {
    /**
     * Get all payments for an order
     * @description Retrieve all payments for an order, including payments from conciliation orders
     */
    get: {
      parameters: {
        path: {
          /** @description Order ID */
          orderId: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Payment"][];
            };
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /**
     * Create a new payment for an order
     * @description Create a new payment for an order using idempotency key. Returns 400 if order already has a payment in status 'SENT' or 'CONFIRMED'
     */
    post: {
      parameters: {
        path: {
          /** @description Order ID */
          orderId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * @description Idempotency key to prevent duplicate payment creation
             * @example unique-key-123
             */
            idempotency_key: string;
          };
        };
      };
      responses: {
        /** @description Payment created successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Payment"];
            };
          };
        };
        /** @description Order already has a payment in status 'SENT' or 'CONFIRMED' */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/customers/{customerId}/messages": {
    /**
     * Get all messages for a customer
     * @description Retrieve all conversation messages for a specific customer
     */
    get: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["ConversationMessage"][];
            };
          };
        };
        /** @description Customer not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /**
     * Send a message to a customer
     * @description Send a text message to a customer via Telegram and save it to CONVERSATION_MESSAGES
     */
    post: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * @description The text message to send
             * @example Hello, this is a test message
             */
            text: string;
          };
        };
      };
      responses: {
        /** @description Message sent successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["ConversationMessage"];
            };
          };
        };
        /** @description Customer not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/comments": {
    /**
     * Get comments
     * @description Retrieve comments with optional filtering by entity_id and class
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter comments by entity ID */
          entity_id?: string;
          /** @description Filter comments by class/type */
          class?: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Comment"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /**
     * Create a comment
     * @description Create a new comment
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * @description The comment text content
             * @example This is a comment
             */
            text: string;
            /**
             * @description ID of the entity this comment belongs to
             * @example order-456
             */
            entity_id: string;
            /**
             * @description The class/type of the comment
             * @example NOTE
             */
            class: string;
          };
        };
      };
      responses: {
        /** @description Comment created successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Comment"];
            };
          };
        };
        /** @description Bad request (e.g., missing required fields) */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/private/items/category/{category}": {
    /**
     * Get items by category
     * @description Retrieve a list of items for a specific category
     */
    get: {
      parameters: {
        path: {
          /** @description Category name */
          category: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Item"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/private/customers/{customerId}/cart/items/{itemId}": {
    /**
     * Add item to cart
     * @description Add an item to a customer's cart
     */
    post: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: number;
          /** @description Item ID */
          itemId: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Item"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/private/customers/{customerId}/orders": {
    /**
     * Create order from cart
     * @description Create a new order from a customer's cart
     */
    post: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: number;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Order"];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/public/users/me": {
    /**
     * Get current user information
     * @description Retrieve the authenticated user's information
     */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["User"];
            };
          };
        };
        /** @description Unauthorized (user not authenticated) */
        401: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/public/signup": {
    /**
     * Register a new user
     * @description Create a new user account
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SignupRequest"];
        };
      };
      responses: {
        /** @description User created successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["User"];
            };
          };
        };
        /** @description Bad request (e.g., email already exists, invalid input) */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/public/login": {
    /**
     * Login a user
     * @description Authenticate a user with email and password
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description User authenticated successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["User"];
            };
          };
        };
        /** @description Bad request (e.g., missing fields, invalid credentials) */
        400: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized (invalid credentials) */
        401: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/agent/deliveries/{id}": {
    /**
     * Get delivery agent overview by ID
     * @description Retrieve delivery agent overview including pickups and deliveries
     */
    get: {
      parameters: {
        path: {
          /** @description Delivery agent ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["DeliveryAgentOverview"];
            };
          };
        };
        /** @description Delivery agent not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Customer: {
      /**
       * @description Customer's first name
       * @example Антон
       */
      first_name?: string;
      /**
       * @description Customer's first name
       * @example Антон
       */
      last_name?: string;
      /**
       * @description Unique identifier for the customer
       * @example 1019705782
       */
      id: string;
      /**
       * @description Whether the customer is a bot
       * @example null
       */
      is_bot?: boolean | null;
      /**
       * @description Customer's language code
       * @example ru
       */
      language_code: string;
      /**
       * @description Customer's username
       * @example getting_drunk
       */
      username?: string;
    };
    CustomerOverview: WithRequired<{
      balance: components["schemas"]["CustomerBalance"];
    } & components["schemas"]["Customer"], "balance">;
    OrderPickingPatch: {
      /** @description Items to update in this order picking */
      items: components["schemas"]["PickingItem"][];
    };
    OrderPatch: {
      /**
       * @description Name of the customer
       * @example Updated Order Name
       */
      name?: string;
    };
    OrderPicking: {
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      id: string;
      delivery: components["schemas"]["DeliveryRef"];
      /** @description Items in this order picking */
      items: components["schemas"]["PickingItem"][];
      owner: components["schemas"]["OwnerRef"];
      /**
       * @description Order picking status
       * @example PENDING
       */
      status: string;
      /**
       * Format: float
       * @description Total value
       * @example 0
       */
      total: number;
      /**
       * @description Order picking type
       * @example ORIGINAL
       */
      type: string;
    };
    CartItem: {
      /**
       * Format: float
       * @description Fraction value
       * @example 0.42
       */
      fraction: number;
      /**
       * @description Item group
       * @example MOSCOW
       */
      group: string;
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      id: string;
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      item_id: string;
      /**
       * @description Item name
       * @example Горгонзола (Бразилия) Кусок 0.42 Кг
       */
      name: string;
      /**
       * Format: float
       * @description Price for the total quantity and fraction
       * @example 609
       */
      price: number;
      /**
       * Format: float
       * @description Price for one unit
       * @example 609
       */
      price_for_unit: number;
      /**
       * @description Quantity
       * @example 1
       */
      quantity: number;
      owner: components["schemas"]["OwnerRef"];
    };
    PickingItem: ({
      /** @enum {unknown} */
      status?: "PENDING" | "COLLECTED" | "CANCELED";
    }) & components["schemas"]["OrderItem"];
    OwnerRef: {
      /**
       * @description Owner ID
       * @example 270053857
       */
      id: string;
    };
    DeliveryRef: {
      /**
       * Format: date-time
       * @description Delivery end date and time
       * @example 2025-11-23T00:00:00.000Z
       */
      delivery_end: string;
      /**
       * Format: date-time
       * @description Delivery start date and time
       * @example 2025-11-21T00:00:00.000Z
       */
      delivery_start: string;
      /**
       * @description Unique identifier for the order picking
       * @example ef4d5632-ba34-4488-97a5-b9b7af299535
       */
      id: string;
    };
    Item: {
      /**
       * @description Item category
       * @example MEAT
       */
      category: string;
      /**
       * @description Item description
       * @example мясо
       */
      description: string;
      /**
       * Format: float
       * @description Fraction value
       * @example 1.2
       */
      fraction: number;
      /**
       * Format: float
       * @description Fraction price out
       * @example 1439
       */
      fraction_price_out: number;
      /**
       * @description Item group
       * @example BALASHOV
       */
      group: string;
      /**
       * @description Unique identifier for the item
       * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
       */
      id: string;
      /**
       * @description Link to item details
       * @example https://t.me/posebestoimosti_saratov/214
       */
      link: string;
      /**
       * @description Item name
       * @example Телятина Филе (Тендер Лоин)
       */
      name: string;
      /**
       * Format: float
       * @description Price in
       * @example 1000
       */
      price_in: number;
      /**
       * Format: float
       * @description Price out
       * @example 1199
       */
      price_out: number;
      /**
       * @description Row number
       * @example 11
       */
      row_number: number;
      /**
       * @description Item status
       * @example ACTIVE
       */
      status: string;
      /**
       * @description Unit of measurement
       * @example Кг
       */
      unit: string;
      /**
       * @description Unit description
       * @example Отруб
       */
      unti_description: string;
    };
    Stats: {
      /**
       * Format: float
       * @description Total value
       * @example 4498
       */
      total: number;
      /**
       * Format: float
       * @description Fraction value
       * @example 1.8
       */
      fraction: number;
      /**
       * Format: integer
       * @description Quantity of items
       * @example 1
       */
      quantity: number;
      /**
       * @description Name of the stats item
       * @example Сёмга филе Филе на коже 1.8 Кг
       */
      name: string;
    };
    DeliveryOverviewItemStats: {
      orders?: components["schemas"]["Order"][];
    } & components["schemas"]["Stats"];
    Delivery: {
      /**
       * @description Unique identifier for the delivery
       * @example delivery-123
       */
      id: string;
      /**
       * @description Delivery number
       * @example 1001
       */
      number: number;
      /**
       * @description Description of the delivery
       * @example Weekly grocery delivery
       */
      description: string;
      /**
       * @description Current status of the delivery
       * @example PENDING
       * @enum {string}
       */
      status: "PENDING" | "IN_TRANSIT" | "IN_TRANSIT_BACK" | "FULFILLED";
      /**
       * Format: date-time
       * @description Deadline for placing orders
       * @example 2025-01-15T23:59:59Z
       */
      order_deadline: string;
      /**
       * Format: date-time
       * @description Start date and time of delivery
       * @example 2025-01-16T08:00:00Z
       */
      delivery_start: string;
      /**
       * Format: date-time
       * @description End date and time of delivery
       * @example 2025-01-16T18:00:00Z
       */
      delivery_end: string;
      /**
       * @description Delivery group identifier
       * @example group-a
       */
      group: string;
      /** @description List of orders in this delivery */
      orders: components["schemas"]["Order"][];
      owner?: components["schemas"]["OwnerRef"];
    };
    DeliveryOverview: {
      /** @description List of active orders in this delivery. All orders which are not CANCELED */
      activeOrders?: components["schemas"]["Order"][];
      /** @description List of active orders in this delivery. All orders which are not CANCELED */
      cancelledOrders?: components["schemas"]["Order"][];
      /** @description List of all CANCELED orders in this delivery */
      removedOrders?: components["schemas"]["Order"][];
      /** @description Statistics for the delivery */
      stats?: components["schemas"]["DeliveryOverviewItemStats"][];
    } & components["schemas"]["Delivery"];
    Order: {
      /**
       * @description Unique identifier for the order
       * @example order-456
       */
      id: string;
      /**
       * @description Original order this order is consolidated with
       * @example order-45611
       */
      reconciliated_order_id?: string;
      /**
       * @description Name of the customer
       * @example Order 1
       */
      name?: string;
      /**
       * @description Address
       * @example Str 1, city
       */
      shippingAddress?: string;
      delivery?: components["schemas"]["DeliveryRef"];
      /** @description Items in this order */
      items: components["schemas"]["CartItem"][];
      /** @enum {string} */
      status: "PENDING" | "PAYMENT_IN_PROGRESS" | "PAYMENT_FAILED" | "PAID" | "RESOLVING" | "CONCILIATION_PAYMENT_IN_PROGRESS" | "CONCILIATED" | "CANCELED";
      /**
       * @description Current status of the order
       * @example PAID
       * @enum {string}
       */
      type: "CONCILIATION" | "ORIGINAL";
      owner: components["schemas"]["OwnerRef"];
      /**
       * @description Number of items in the order
       * @example 5
       */
      number_of_items?: number;
      /**
       * Format: float
       * @description Total value of the order
       * @example 150.75
       */
      total: number;
    };
    OrderOverview: WithRequired<{
      picking?: components["schemas"]["OrderPicking"];
      customer: components["schemas"]["CustomerOverview"];
      comments?: components["schemas"]["Comment"];
    } & components["schemas"]["Order"], "customer">;
    User: {
      /**
       * @description Unique identifier for the user
       * @example user-123
       */
      id: string;
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * Format: hash
       * @description hashed password
       * @example sdfee335gsdfwDEfggh
       */
      password?: string;
      /**
       * Format: jwt
       * @description jwt token
       * @example sdfee335gsdfwDEfggh
       */
      token?: string;
      /** @description User roles */
      roles: ("AGENT" | "ADMIN")[];
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-01T00:00:00Z
       */
      created_at?: string;
      /** @description User label information */
      label?: {
        /**
         * @description Label expiration timestamp
         * @example 1735689600
         */
        expiration?: number;
      };
    };
    Error: {
      error: {
        /**
         * @description Error code
         * @example NOT_FOUND
         */
        code: string;
        /**
         * @description Error message
         * @example Delivery not found
         */
        message: string;
      };
    };
    /** @description A message sent in a conversation */
    ConversationMessage: {
      /** @description Unique identifier for the message */
      id: string;
      /** @description Unique identifier a thread those messages belongs to */
      thread_id?: string;
      /**
       * @description The provider used to send the message
       * @enum {string}
       */
      provider: "TELEGRAM" | "OTHER";
      /**
       * @description The provider used to send the message
       * @enum {string}
       */
      role: "CUSTOMER" | "ADMIN";
      /** @description The chat ID where the message was sent */
      recipient_id?: string;
      /** @description The content of the message */
      text: string;
      /**
       * Format: date-time
       * @description Timestamp when the message was created
       */
      created_at: string;
    };
    Payment: {
      /**
       * @description URL for payment processing
       * @example https://securepay.tinkoff.ru/payment/init
       */
      payment_url: string;
      /**
       * @description Error code from payment provider
       * @example 0
       */
      error_code?: number | null;
      /** @enum {string} */
      status: "SENT" | "CONFIRMED" | "FAILED" | "TIMED_OUT" | "CANCELED" | "REJECTED";
      /**
       * @description Internal payment ID
       * @example payment-123456
       */
      id: string;
      /**
       * @description Payment ID from external payment provider
       * @example 123456
       */
      external_id: string;
      /**
       * @description Terminal key from payment provider
       * @example TinkoffBankTest
       */
      terminal_key: string;
      /**
       * @description Order ID associated with the payment
       * @example order-456
       */
      order_id: string;
      /**
       * @description Payment amount in minor units (kopecks)
       * @example 15000
       */
      amount: number;
      /**
       * @description Payment amount in minor units (kopecks)
       * @example 15000
       */
      total: number;
      /**
       * @description Whether the payment was successful
       * @example true
       */
      success: boolean;
      /**
       * Format: date-time
       * @description Payment creation timestamp
       * @example 2025-01-10T14:30:00Z
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Payment creation timestamp
       * @example 2025-01-10T14:30:00Z
       */
      updated_at: string;
      /**
       * Format: date-time
       * @description Payment creation timestamp
       * @example 2025-01-10T14:30:00Z
       */
      confirmed_at?: string;
    };
    CustomerBalance: {
      /**
       * @description Internal payment ID
       * @example payment-123456
       */
      id: string;
      owner: components["schemas"]["OwnerRef"];
      /**
       * Format: float
       * @description Customer balance amount
       * @example 150.75
       */
      value: number;
      /**
       * Format: date-time
       * @description Balance creation timestamp
       * @example 2025-01-10T14:30:00Z
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description Balance last update timestamp
       * @example 2025-01-10T14:30:00Z
       */
      updated_at?: string;
    };
    SignupRequest: {
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User's password (min 6 characters)
       * @example password123
       */
      password: string;
    };
    LoginRequest: {
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User's password
       * @example password123
       */
      password: string;
    };
    Comment: {
      /**
       * @description The comment text content
       * @example This is a comment
       */
      text: string;
      /** @description The owner of the comment */
      owner: components["schemas"]["OwnerRef"];
      /**
       * Format: date-time
       * @description Timestamp when the comment was created
       * @example 2025-01-10T14:30:00Z
       */
      created_at: string;
      /**
       * @description Unique identifier for the comment
       * @example comment-123456
       */
      id: string;
      /**
       * @description ID of the entity this comment belongs to
       * @example order-456
       */
      entity_id: string;
      /**
       * @description The class/type of the comment
       * @example NOTE
       */
      class: string;
    };
    DeliveryAgentOverview: {
      /**
       * @description Unique identifier for the delivery agent
       * @example agent-123
       */
      id: string;
      /**
       * @description Name of the delivery agent
       * @example John Doe
       */
      name: string;
      /** @description List of pickup orders */
      pickups: components["schemas"]["Order"][];
      /** @description List of delivery orders */
      deliveries: components["schemas"]["Order"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
