/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description An event stored in the Firestore outbox that represents a domain change
     * requiring asynchronous processing (e.g., ORDER_RESOLVED → trigger payment).
     * Written atomically with the domain write using the Outbox Pattern.
     */
    OutboxEvent: {
      /** @description Unique event identifier (UUID or Firestore doc ID). */
      id: string;
      /**
       * @description Type of event that occurred.
       * @example ORDER_RESOLVED
       */
      type: string;
      /**
       * @description Arbitrary event-specific data.
       * @example {
       *   "orderId": "abc123",
       *   "amount": 4999
       * }
       */
      payload: Record<string, never>;
      /**
       * Format: date-time
       * @description Timestamp when the event was written to Firestore.
       */
      createdAt: string;
      /**
       * @description Indicates whether the event has been successfully processed.
       * @default false
       */
      processed: boolean;
      /**
       * Format: date-time
       * @description Timestamp when processing completed successfully.
       */
      processedAt?: string | null;
      /**
       * @description How many times the event has failed processing.
       * @default 0
       */
      retries: number;
      /** @description Error message from the last failed processing attempt. */
      lastError?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
