/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An event stored in the Firestore outbox that represents a domain change
         *     requiring asynchronous processing (e.g., ORDER_RESOLVED → trigger payment).
         *     Written atomically with the domain write using the Outbox Pattern.
         */
        BaseOutboxEvent: {
            /** @description Unique event identifier (UUID or Firestore doc ID). */
            readonly id: string;
            /** @description Idempotency key, used if sibling events are idempotent */
            readonly idempotent_key?: string;
            /**
             * @description Type of event that occurred.
             * @example ORDER_RESOLVED
             */
            type: string;
            /**
             * Format: date-time
             * @description Timestamp when the event was written to Firestore.
             */
            created_at: string;
            /**
             * @description Indicates whether the event has been successfully processed.
             * @default false
             */
            processed: boolean;
            /**
             * Format: date-time
             * @description Timestamp when processing completed successfully.
             */
            processedAt?: string | null;
            /**
             * @description How many times the event has failed processing.
             * @default 0
             */
            retries: number;
            /** @description Error message from the last failed processing attempt. */
            lastError?: string | null;
        };
        BalanceChangeEvent: {
            /** @description Unique event identifier (UUID or Firestore doc ID). */
            readonly id: string;
            /** @description Id of the balance to change */
            readonly balance_id?: string;
            /**
             * Format: date-time
             * @description Timestamp when the event was written to Firestore.
             */
            created_at: string;
            /**
             * @description How balance has changed
             * @default 0
             */
            change: number;
            /** @enum {string} */
            reason: "ORDER_RESOLVED" | "SUBSCRIPTION_CHARGE";
        };
        Payment: {
            /**
             * @description Total payment amount
             * @example 1668
             */
            total: string;
            /**
             * @description Current payment status
             * @example PENDING
             */
            status: string;
            /**
             * @description Identifier of the payer
             * @example 270053857
             */
            payer_id: string;
            /**
             * @description Identifier of the associated order
             * @example FZcMTsLGnRHo87gZRS66
             */
            order_id: string;
        };
        TinkoffPaymentItem: {
            Name: string;
            Price: number;
            Quantity: number;
            Amount: number;
            /** @enum {string} */
            Tax: "none" | "vat0" | "vat10" | "vat20" | "vat110" | "vat120";
        };
        TinkoffReceipt: {
            /** Format: email */
            Email: string;
            /** @description Телефон покупателя */
            Phone?: string;
            /** @enum {string} */
            Taxation: "osn" | "usn_income" | "usn_income_outcome" | "envd" | "esn" | "patent";
            Items: components["schemas"]["TinkoffPaymentItem"][];
        };
        TinkoffPaymentData: {
            /** @description Телефон покупателя */
            Phone?: string;
            /**
             * Format: email
             * @description Электронная почта покупателя
             */
            Email?: string;
        };
        TinkoffPaymentPayload: {
            /** @description Ключ терминала */
            TerminalKey: string;
            Token: string;
            /** @description Сумма в копейках */
            Amount: number;
            /** @description Идентификатор заказа */
            OrderId: string;
            /** @description Идентификатор платежа */
            PaymentId?: string;
            /** @description Описание заказа */
            Description?: string;
            /** Format: date-time */
            RedirectDueDate: string;
            DATA?: components["schemas"]["TinkoffPaymentData"];
            Receipt: components["schemas"]["TinkoffReceipt"];
        };
        TinkoffPaymentCancelationRequest: {
            /** @description Ключ терминала */
            TerminalKey: string;
            Token: string;
            /** @description Идентификатор платежа */
            PaymentId?: string;
        };
        TinkoffChargeRequest: {
            /** @description Ключ терминала */
            TerminalKey: string;
            Token: string;
            /** @description Идентификатор платежа */
            PaymentId?: string;
            /** @description Уникальный идентификатор сохраненных реквизитов карты покупателя. */
            RebillId?: string;
        };
        TinkoffResult: {
            /** @example TBankTest */
            TerminalKey: string;
            /** @example 21057 */
            OrderId: string;
            /** @example true */
            Success: boolean;
            /** @example REVERSED */
            Status: string;
            /** @example 13000 */
            OriginalAmount: number;
            /** @example 13000 */
            Amount: number;
            /** @example 5000 */
            NewAmount: number;
            /** @example 2304882 */
            PaymentId: string;
            /** @example 0 */
            ErrorCode: string;
            /** @example OK */
            Message: string;
            /** @example None */
            Details: string | null;
            /** @example 756478567845678436 */
            ExternalRequestId: string;
            /** @example https://pay.tbank.ru/new/fU1ppgqa */
            PaymentURL?: string;
        };
        /** @description A task for broadcasting messages */
        BroadcastTask: {
            /** @description Unique task identifier */
            id: string;
            /**
             * Format: date-time
             * @description Timestamp when the task was created
             */
            created_at: string;
            /** @description Whether the task has finished */
            finished: boolean;
            /** @description Last processed identifier */
            last_id?: string;
            /** @description Message to broadcast */
            message: string;
            /**
             * @description Message format (e.g., HTML, plain text)
             * @enum {enum}
             */
            format: "HTML" | "Markdown" | "Plaintext";
            /** @description Number of tries for the broadcast task */
            number_of_runs: number;
            /** @description Number of customers to process in each batch */
            batch_size: number;
            /**
             * Format: date-time
             * @description Timestamp when the task was last updated
             */
            updated_at: string;
        };
        /**
         * @description Общий ответ агента подбора моторного масла. Набор заполненных полей
         *     зависит от значения status. Все поля, кроме status, могут быть null.
         */
        OilAgentResponse: {
            /**
             * @description Статус ответа:
             *     * need_more_info — требуется дополнительная информация об автомобиле;
             *     * success — масло найдено;
             *     * not_found — подходящего масла нет;
             *     * unknown — невозможно надёжно определить требования.
             * @example success
             * @enum {string}
             */
            status: "need_more_info" | "success" | "not_found" | "unknown";
            /**
             * @description Уточняющий вопрос пользователю (для статуса need_more_info)
             * @example Какой двигатель установлен на вашем автомобиле?
             */
            question?: string | null;
            /** @description Описание автомобиля, определённое агентом (для статусов success и not_found) */
            car?: {
                /**
                 * @description Марка автомобиля
                 * @example Volkswagen
                 */
                make: string;
                /**
                 * @description Модель автомобиля
                 * @example Passat
                 */
                model: string;
                /**
                 * @description Год выпуска автомобиля
                 * @example 2019
                 */
                year: number;
                /**
                 * @description Описание двигателя (объём, мощность, тип топлива и т.п.)
                 * @example 2.0 TDI 150 hp
                 */
                engine: string;
            } | null;
            /** @description Требования производителя к моторному маслу (для статусов success и not_found) */
            requirements?: {
                /**
                 * @description Требуемая вязкость по SAE
                 * @example [
                 *       "5W-30"
                 *     ]
                 */
                sae: string[];
                /**
                 * @description Требуемые допуски ACEA
                 * @example [
                 *       "C3"
                 *     ]
                 */
                acea: string[];
                /**
                 * @description Требуемые допуски API
                 * @example []
                 */
                api: string[];
                /**
                 * @description Требуемые OEM-допуски производителя автомобиля
                 * @example [
                 *       "VW 507 00"
                 *     ]
                 */
                oemApprovals: string[];
            } | null;
            /**
             * @description Идентификаторы рекомендованных масел (для статусов success и not_found)
             * @example [
             *       "oil_001"
             *     ]
             */
            recommendedOilIds?: string[] | null;
            /**
             * @description Обоснование результата подбора или причина его отсутствия
             * @example Масло соответствует требуемому допуску производителя VW 507 00.
             */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
