import * as moment from "moment";

import {ChargeSubscriptionEvent, Payment} from "../../models";
import PaymentService from "../PaymentService";
import TelegramService from "../TelegramService";
import AbstractProcessor from "./AbstractProcessor";
import {toMessage} from "../../messaging/util";
import {error} from "firebase-functions/logger";
import SubscriptionService from "../SubscriptionService";
import CustomerService from "../CustomerService";
import TBankService from "../../services/payments/TBankService";
import CustomerBalanceService from "../CustomerBalanceService";


class ChargeSubscriptionProcessor extends AbstractProcessor {
  async process(event: ChargeSubscriptionEvent): Promise<void> {
    const subscriptionService = new SubscriptionService(this.db);
    const customerService = new CustomerService(this.db);
    const paymentService = new PaymentService(this.db);
    const customerBalanceService = new CustomerBalanceService(this.db);
    const telegramService = new TelegramService();
    const tbankService = new TBankService();

    const subscriptionId = event.payload.subscription_id;

    const subscription = await subscriptionService.require(subscriptionId);

    const balance = await customerBalanceService.obtainForCustomer(subscriptionId);
    const now = new Date();

    const balancedFee = Math.min(300, balance.value); // negative balance means that we owe money to customer

    const toCharge = 300 - balancedFee;

    if (!toCharge) {
      /**
       * Fee will be charged from the customers balance
       */
      const payment: Payment = {
        id: "", // will be generated by paymentService.add
        external_id: `${subscriptionId}-charged-from-balance`, // will be set after initPayment
        terminal_key: "no-terminal-used",
        payment_url: "",
        order_id: `${subscriptionId}-${now.getFullYear()}-${now.getMonth()}-${now.getDay()}-${crypto.randomUUID().substring(0, 5)}`,
        amount: toCharge,
        total: toCharge,
        status: "CONFIRMED",
        success: true,
        created_at: now,
        updated_at: now,
        error_code: "",
      };
      const newNextPayment = moment(subscription.next_payment_at).add(1, "month").toDate();

      const ref = subscriptionService.getObjectRef(subscriptionId);
      await ref.update({next_payment_at: newNextPayment});
      await customerBalanceService.updateBalance(subscriptionId, -300, "SUBSCRIPTION_CHARGE");
      await paymentService.add(payment);
      return;
    }

    const accounting = await customerService.obtainAccounting(subscriptionId);
    if (!accounting.rebill_id) {
      throw new Error(`No rebill_id found for customer ${subscriptionId}`);
    }

    const paymentRequest = tbankService.subscriptionToPaymentRequest({...subscription, fee: toCharge}, true);
    const p = await tbankService.initPayment(paymentRequest);

    const payment: Payment = {
      id: "", // will be generated by paymentService.add
      external_id: p.PaymentId, // will be set after initPayment
      terminal_key: p.TerminalKey,
      payment_url: "",
      order_id: p.OrderId,
      amount: p.Amount,
      total: p.Amount,
      status: "CONFIRMED",
      success: true,
      created_at: new Date(),
      updated_at: new Date(),
      error_code: p.ErrorCode,
      message: p.Message,
    };

    const savedPayment = await paymentService.add(payment);

    const rebillId = accounting.rebill_id;

    const chargeRequest = tbankService.paymentToChargeRequest(savedPayment, rebillId);
    const chargeResult = await tbankService.charge(chargeRequest);

    const adminTemplateValues = {
      subscriptionId,
    };

    if (!chargeResult.Success) {
      await paymentService.update(savedPayment, {
        status: "FAILED",
        success: false,
        updated_at: new Date(),
        error_code: chargeResult.ErrorCode || "UNKNOWN",
      });
      const adminMessage = toMessage("SUBSCRIPTION_PAYMENT_FAILED_ADMIN", adminTemplateValues);
      await telegramService.sendMessage("270053857", adminMessage, subscriptionId).catch((e) => error(`Failed to send SUBSCRIPTION_PAYMENT_CONFIRMED_ADMIN to 270053857 : ${e}`));
      return;
    }

    const newNextPayment = moment(subscription.next_payment_at).add(1, "month").toDate();
    await subscriptionService.update(subscription, {
      next_payment_at: newNextPayment,
    });

    await paymentService.update(savedPayment, {
      status: "CONFIRMED",
      success: true,
      updated_at: new Date(),
    });

    if (balancedFee) {
      await customerBalanceService.updateBalance(subscriptionId, -balancedFee, "SUBSCRIPTION_CHARGE");
    }

    const adminMessage = toMessage("SUBSCRIPTION_PAYMENT_CONFIRMED_ADMIN", adminTemplateValues);
    await telegramService.sendMessage("270053857", adminMessage, subscriptionId).catch((e) => error(`Failed to send SUBSCRIPTION_PAYMENT_CONFIRMED_ADMIN to 270053857 : ${e}`));
  }
}

export default ChargeSubscriptionProcessor;
