/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all deliveries
         * @description Retrieve a list of all deliveries
         */
        get: operations["getAllDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get delivery by ID
         * @description Retrieve a specific delivery by its ID
         */
        get: operations["getDeliveryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/deliveries/{id}/stats/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get delivery statistics in CSV format
         * @description Retrieve delivery order statistics filtered by status and export as CSV
         */
        get: operations["getDeliveryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order overview by ID
         * @description Retrieve a specific delivery by its ID
         */
        get: operations["getOrderOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an order
         * @description Update an order's name
         */
        patch: operations["updateOrder"];
        trace?: never;
    };
    "/admin/order-pickings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order picking items
         * @description Update the items in an order picking
         */
        patch: operations["updateOrderPicking"];
        trace?: never;
    };
    "/admin/order-pickings/{pickingId}/items/{itemId}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Collect an item in an order picking
         * @description Mark an item in an order picking as collected.
         */
        post: operations["collectOrderPickingItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}/order-picking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start order picking process
         * @description Check if order picking exists, return existing one or create new from order
         */
        post: operations["startOrderPicking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}/consolidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve an order
         * @description Marks an order as resolved.
         */
        post: operations["consolidateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cancel an order
         * @description Cancel an order and emit OrderCancelledEvent. Order can only be cancelled if status is PENDING, PAYMENT_IN_PROGRESS, PAYMENT_FAILED, or PAID.
         */
        put: operations["cancelOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{id}/conciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get conciliation order
         * @description Retrieve the conciliation order for a given order ID
         */
        get: operations["getConciliationOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{orderId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all payments for an order
         * @description Retrieve all payments for an order, including payments from conciliation orders
         */
        get: operations["getPaymentsForOrder"];
        put?: never;
        /**
         * Create a new payment for an order
         * @description Create a new payment for an order using idempotency key. Returns 400 if order already has a payment in status 'SENT' or 'CONFIRMED'
         */
        post: operations["createPaymentForOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers/{customerId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all messages for a customer
         * @description Retrieve all conversation messages for a specific customer
         */
        get: operations["getMessagesForCustomer"];
        put?: never;
        /**
         * Send a message to a customer
         * @description Send a text message to a customer via Telegram and save it to CONVERSATION_MESSAGES
         */
        post: operations["sendMessageToCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get comments
         * @description Retrieve comments with optional filtering by entity_id and class
         */
        get: operations["getComments"];
        put?: never;
        /**
         * Create a comment
         * @description Create a new comment
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new broadcast task
         * @description Create a new broadcast task with the given message.
         */
        post: operations["createBroadcastTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/broadcast/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a broadcast task once
         * @description Pick BroadcastTask from DB and run the task once using BroadcastService, returning list of BroadcastResult objects.
         */
        post: operations["runBroadcastTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/items/category/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get items by category
         * @description Retrieve a list of items for a specific category
         */
        get: operations["getItemsByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get item overview for a customer
         * @description Retrieve item overview for a specific customer and item
         */
        get: operations["getCustomerItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cart items for a customer
         * @description Retrieve all items in a customer's cart
         */
        get: operations["getCartItems"];
        put?: never;
        /**
         * Add item to cart
         * @description Add an item to a customer's cart
         */
        post: operations["addItemToCart"];
        /**
         * Remove item from cart
         * @description Remove an item from a customer's cart
         */
        delete: operations["removeItemFromCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/cart/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create order from cart and initialize payment
         * @description Transactionally and idempotently fetch all cart items for the customer, split them by group, create separate orders for each group, find earliest delivery for each group, assign deliveries, initialize payment for each order, and return created orders and payments
         */
        post: operations["createOrderAndPaymentFromCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a subscription for a customer
         * @description Create a new subscription for a customer. If customer already has an active subscription which is not passed due (current date is before next_payment_date) throw bad request. If there is no active subscription for user create one and set next_payment_date month ahead.
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all orders for a customer
         * @description Retrieve a list of all orders for a specific customer
         */
        get: operations["getCustomerOrders"];
        put?: never;
        /**
         * Create order from cart
         * @description Create a new order from a customer's cart
         */
        post: operations["createOrderFromCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer overview
         * @description Retrieve customer overview including balance, stats, and subscription
         */
        get: operations["getCustomerOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/customers/{customerId}/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get banks for a customer
         * @description Retrieve a list of banks associated with a customer
         */
        get: operations["getCustomerBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user information
         * @description Retrieve the authenticated user's information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Create a new user account
         */
        post: operations["signupUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login a user
         * @description Authenticate a user with email and password
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get delivery agent overview by ID
         * @description Retrieve delivery agent overview including pickups and deliveries
         */
        get: operations["getDeliveryAgentOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/orders/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Mark order as delivered
         * @description Set order status to DELIVERED
         */
        put: operations["markOrderAsDelivered"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Customer: {
            /**
             * @description Customer's first name
             * @example Антон
             */
            first_name?: string;
            /**
             * @description Customer's first name
             * @example Антон
             */
            last_name?: string;
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * @description Whether the customer is a bot
             * @example null
             */
            is_bot?: boolean | null;
            /**
             * @description Customer's language code
             * @example ru
             */
            language_code?: string;
            /**
             * @description Customer's username
             * @example getting_drunk
             */
            username?: string;
        };
        Subscription: {
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * Format: date-time
             * @description When subscription was created
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description When subscription was canceled
             * @example 2025-11-23T00:00:00.000Z
             */
            canceled_at?: string;
            /**
             * Format: date-time
             * @description When to charge next payment
             * @example 2025-11-23T00:00:00.000Z
             */
            next_payment_at: string;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "CANCELED" | "CANCELED_PAYMENT_OVERDUE";
            /**
             * Format: float
             * @description Cost of the subscription
             * @example 609
             */
            fee: number;
        };
        CustomerOverview: {
            balance: components["schemas"]["CustomerBalance"];
            stats?: components["schemas"]["CustomerStats"];
            subscription?: components["schemas"]["Subscription"];
        } & components["schemas"]["Customer"];
        OrderPickingPatch: {
            /** @description Items to update in this order picking */
            items: components["schemas"]["PickingItem"][];
        };
        OrderPatch: {
            /**
             * @description Name of the customer
             * @example Updated Order Name
             */
            name?: string;
            /**
             * @description Address of shipping
             * @example Oak str 1.
             */
            shipping_address?: string;
        };
        OrderPicking: {
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            id: string;
            delivery: components["schemas"]["DeliveryRef"];
            /** @description Items in this order picking */
            items: components["schemas"]["PickingItem"][];
            owner: components["schemas"]["OwnerRef"];
            /**
             * @description Order picking status
             * @example PENDING
             */
            status: string;
            /**
             * Format: float
             * @description Total value
             * @example 0
             */
            total: number;
            /**
             * @description Order picking type
             * @example ORIGINAL
             */
            type: string;
        };
        CartItem: {
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * Format: float
             * @description Fraction value
             * @example 0.42
             */
            fraction: number;
            /**
             * @description Item group
             * @example MOSCOW
             */
            group: string;
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            id: string;
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            item_id: string;
            /**
             * @description Item name
             * @example Горгонзола (Бразилия) Кусок 0.42 Кг
             */
            name: string;
            /**
             * Format: float
             * @description Price for the total quantity and fraction
             * @example 609
             */
            price: number;
            /**
             * Format: float
             * @description Price for one unit
             * @example 609
             */
            price_for_unit: number;
            /**
             * @description Quantity
             * @example 1
             */
            quantity: number;
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at?: string;
        };
        PickingItem: {
            /** @enum {string} */
            status?: "PENDING" | "COLLECTED" | "CANCELED";
        } & components["schemas"]["CartItem"];
        ItemOverview: {
            /** @description Deliveries containing this item group */
            deliveries?: components["schemas"]["DeliveryRef"][];
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * @description Item description
             * @example мясо
             */
            description: string;
            /**
             * @description Is item sells by weight
             * @example true
             */
            is_weighted: boolean;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.2
             */
            fraction: number;
            /**
             * Format: float
             * @description Fraction price out
             * @example 1439
             */
            fraction_price_out: number;
            /**
             * @description Item group
             * @example BALASHOV
             */
            group: string;
            /**
             * @description Unique identifier for the item
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            id: string;
            /**
             * @description Link to item details
             * @example https://t.me/posebestoimosti_saratov/214
             */
            link: string;
            /**
             * @description Item name
             * @example Телятина Филе (Тендер Лоин)
             */
            name: string;
            /**
             * Format: float
             * @description Price out
             * @example 1199
             */
            price_out: number;
            /**
             * @description Unit of measurement
             * @example Кг
             */
            unit: string;
            /**
             * @description Unit description
             * @example Отруб
             */
            unit_description: string;
            /** @description Statistics for the item including likes and share enters */
            stats?: components["schemas"]["ItemStats"];
        };
        OwnerRef: {
            /**
             * @description Owner ID
             * @example 270053857
             */
            id: string;
        };
        DeliveryRef: {
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            delivery_end: string;
            /**
             * Format: date-time
             * @description Delivery start date and time
             * @example 2025-11-21T00:00:00.000Z
             */
            delivery_start: string;
            /**
             * @description Unique identifier for the order picking
             * @example ef4d5632-ba34-4488-97a5-b9b7af299535
             */
            id: string;
        };
        CustomerRef: {
            /**
             * @description Customer ID
             * @example 1019705782
             */
            id: string;
            /**
             * @description Customer's username
             * @example getting_drunk
             */
            username?: string;
            /**
             * @description Customer's first name
             * @example Антон
             */
            first_name?: string;
            /**
             * @description Customer's last name
             * @example Антон
             */
            last_name?: string;
        };
        Item: {
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * @description Item description
             * @example мясо
             */
            description: string;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.2
             */
            fraction: number;
            /**
             * Format: float
             * @description Fraction price out
             * @example 1439
             */
            fraction_price_out: number;
            /**
             * Format: float
             * @description Fraction price out for non-members
             * @example 1439
             */
            non_member_fraction_price_out?: number;
            /**
             * @description Item group
             * @example BALASHOV
             */
            group: string;
            /**
             * @description Unique identifier for the item
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            id: string;
            /**
             * @description Link to item details
             * @example https://t.me/posebestoimosti_saratov/214
             */
            link: string;
            /**
             * @description Item name
             * @example Телятина Филе (Тендер Лоин)
             */
            name: string;
            /**
             * Format: float
             * @description Price in
             * @example 1000
             */
            price_in: number;
            /**
             * Format: float
             * @description Price out
             * @example 1199
             */
            price_out: number;
            /**
             * @description Row number
             * @example 11
             */
            row_number: number;
            /**
             * @description Item status
             * @example ACTIVE
             */
            status: string;
            /**
             * @description Unit of measurement
             * @example Кг
             */
            unit: string;
            /**
             * @description Unit description
             * @example Отруб
             */
            unit_description: string;
            /**
             * @description Is item sells by weight
             * @example true
             */
            is_weighted: boolean;
        };
        Stats: {
            /**
             * Format: float
             * @description Total value
             * @example 4498
             */
            total: number;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.8
             */
            fraction: number;
            /**
             * Format: integer
             * @description Quantity of items
             * @example 1
             */
            quantity: number;
            /**
             * @description Name of the stats item
             * @example Сёмга филе Филе на коже 1.8 Кг
             */
            name: string;
            /**
             * @description Category of the stats item
             * @example Сёмга филе Филе на коже 1.8 Кг
             */
            category: string;
        };
        ItemStats: {
            /**
             * @description Number of likes for the item
             * @example 42
             */
            number_of_likes?: number;
            /**
             * @description Number of share enters for the item
             * @example 15
             */
            number_of_share_enters?: number;
        };
        DeliveryOverviewItemStats: {
            orders?: components["schemas"]["Order"][];
        } & components["schemas"]["Stats"];
        Delivery: {
            /**
             * @description Unique identifier for the delivery
             * @example delivery-123
             */
            id: string;
            /**
             * @description Delivery number
             * @example 1001
             */
            number: number;
            /**
             * @description Description of the delivery
             * @example Weekly grocery delivery
             */
            description: string;
            /**
             * @description Current status of the delivery
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "IN_TRANSIT" | "IN_TRANSIT_BACK" | "FULFILLED";
            /**
             * Format: date-time
             * @description Deadline for placing orders
             * @example 2025-01-15T23:59:59Z
             */
            order_deadline: string;
            /**
             * Format: date-time
             * @description Start date and time of delivery
             * @example 2025-01-16T08:00:00Z
             */
            delivery_start: string;
            /**
             * Format: date-time
             * @description End date and time of delivery
             * @example 2025-01-16T18:00:00Z
             */
            delivery_end: string;
            /**
             * @description Delivery group identifier
             * @example group-a
             */
            group: string;
            /** @description List of orders in this delivery */
            orders: components["schemas"]["Order"][];
            owner?: components["schemas"]["OwnerRef"];
        };
        DeliveryOverview: {
            /** @description List of active orders in this delivery. All orders which are not CANCELED */
            activeOrders?: components["schemas"]["Order"][];
            /** @description List of active orders in this delivery. All orders which are not CANCELED */
            cancelledOrders?: components["schemas"]["Order"][];
            /** @description List of all CANCELED orders in this delivery */
            removedOrders?: components["schemas"]["Order"][];
            /** @description Statistics for the delivery */
            stats?: components["schemas"]["DeliveryOverviewItemStats"][];
        } & components["schemas"]["Delivery"];
        Order: {
            /**
             * @description Unique identifier for the order
             * @example order-456
             */
            id: string;
            /**
             * @description Original order this order is consolidated with
             * @example order-45611
             */
            reconciliated_order_id?: string;
            /**
             * @description Name of the customer
             * @example Order 1
             */
            name?: string;
            /**
             * @description Address
             * @example Str 1, city
             */
            shipping_address?: string;
            delivery?: components["schemas"]["DeliveryRef"];
            /** @description Items in this order */
            items: components["schemas"]["CartItem"][];
            /** @enum {string} */
            status: "PENDING" | "PAYMENT_IN_PROGRESS" | "PAYMENT_FAILED" | "PAID" | "RESOLVING" | "CONCILIATION_PAYMENT_IN_PROGRESS" | "CONSOLIDATION_SUCCESSFUL" | "CONCILIATED" | "CANCELED" | "DELIVERED";
            /**
             * @description Current status of the order
             * @example CONCILIATION
             * @enum {string}
             */
            type: "CONCILIATION" | "ORIGINAL";
            owner: components["schemas"]["OwnerRef"];
            /**
             * @description Number of items in the order
             * @example 5
             */
            number_of_items?: number;
            /**
             * Format: float
             * @description Total value of the order
             * @example 150.75
             */
            total: number;
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            updated_at: string;
        };
        OrderOverview: {
            picking?: components["schemas"]["OrderPicking"];
            customer: components["schemas"]["CustomerOverview"];
            comments?: components["schemas"]["Comment"];
            payment?: components["schemas"]["Payment"];
        } & components["schemas"]["Order"];
        User: {
            /**
             * @description Unique identifier for the user
             * @example user-123
             */
            id: string;
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * Format: hash
             * @description hashed password
             * @example sdfee335gsdfwDEfggh
             */
            password?: string;
            /**
             * Format: jwt
             * @description jwt token
             * @example sdfee335gsdfwDEfggh
             */
            token?: string;
            /** @description User roles */
            roles: ("AGENT" | "ADMIN")[];
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-01-01T00:00:00Z
             */
            created_at?: string;
            /** @description User label information */
            label?: {
                /**
                 * @description Label expiration timestamp
                 * @example 1735689600
                 */
                expiration?: number;
            };
        };
        Error: {
            error: {
                /**
                 * @description Error code
                 * @example NOT_FOUND
                 */
                code: string;
                /**
                 * @description Error message
                 * @example Delivery not found
                 */
                message: string;
            };
        };
        /** @description A message sent in a conversation */
        ConversationMessage: {
            /** @description Unique identifier for the message */
            readonly id: string;
            /** @description Unique identifier a thread those messages belongs to */
            thread_id: string;
            /**
             * @description The provider used to send the message
             * @enum {string}
             */
            provider: "TELEGRAM" | "OTHER";
            /**
             * @description The provider used to send the message
             * @enum {string}
             */
            role: "CUSTOMER" | "ADMIN";
            /** @description The chat ID where the message was sent */
            recipient_id?: string;
            /** @description The content of the message */
            text: string;
            /**
             * Format: date-time
             * @description Timestamp when the message was created
             */
            created_at: string;
        };
        Payment: {
            /**
             * @description URL for payment processing
             * @example https://securepay.tinkoff.ru/payment/init
             */
            payment_url: string;
            /**
             * @description Error code from payment provider
             * @example 0
             */
            error_code?: string | null;
            /**
             * @description Message from payment provider
             * @example 0
             */
            message?: string | null;
            /** @enum {string} */
            status: "SENT" | "CONFIRMED" | "FAILED" | "TIMED_OUT" | "CANCELED" | "REJECTED";
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            /**
             * @description Payment ID from external payment provider
             * @example 123456
             */
            external_id: string;
            /**
             * @description Terminal key from payment provider
             * @example TinkoffBankTest
             */
            terminal_key: string;
            /**
             * @description Order ID associated with the payment
             * @example order-456
             */
            order_id: string;
            /**
             * @description Payment amount in minor units (kopecks)
             * @example 15000
             */
            amount: number;
            /**
             * @description Payment amount in minor units (kopecks)
             * @example 15000
             */
            total: number;
            /**
             * @description Whether the payment was successful
             * @example true
             */
            success: boolean;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            updated_at: string;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            confirmed_at?: string;
        };
        CustomerBalance: {
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: float
             * @description Customer balance amount
             * @example 150.75
             */
            value: number;
            /**
             * Format: date-time
             * @description Balance creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Balance last update timestamp
             * @example 2025-01-10T14:30:00Z
             */
            updated_at?: string;
        };
        CustomerAccounting: {
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            /**
             * @description Id at bank to charge recursive payments
             * @example some-id-here
             */
            rebill_id: string;
        };
        CustomerStats: {
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_orders: number;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_active_orders: number;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_free_orders: number;
            /**
             * @description Number of canceled orders for the customer
             * @example 2
             */
            number_of_canceled_orders: number;
            /**
             * @description Number of fulfilled orders for the customer
             * @example 7
             */
            number_of_fulfilled_orders: number;
            /**
             * @description Number of paid subscription months for the customer
             * @example 3
             */
            number_of_paid_months: number;
            /**
             * Format: float
             * @description Total amount paid by the customer
             * @example 4500.75
             */
            paid_in_total: number;
        };
        SignupRequest: {
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User's password (min 6 characters)
             * @example password123
             */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User's password
             * @example password123
             */
            password: string;
        };
        AddToCartItem: {
            /**
             * @description Item ID to add to cart
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            itemId: string;
        };
        RemoveFromCartItem: {
            /**
             * @description Cart item ID to remove from cart
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            cartItemId?: string;
            /**
             * @description item ID to remove from cart. All the cart items of this item will be removed
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            itemId?: string;
        };
        Comment: {
            /**
             * @description The comment text content
             * @example This is a comment
             */
            text: string;
            /** @description The owner of the comment */
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: date-time
             * @description Timestamp when the comment was created
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /**
             * @description Unique identifier for the comment
             * @example comment-123456
             */
            id: string;
            /**
             * @description ID of the entity this comment belongs to
             * @example order-456
             */
            entity_id: string;
            /**
             * @description The class/type of the comment
             * @example NOTE
             */
            class: string;
        };
        DeliveryAgentOverview: {
            /**
             * @description Unique identifier for the delivery agent
             * @example agent-123
             */
            id: string;
            /**
             * @description Name of the delivery agent
             * @example John Doe
             */
            name: string;
            /** @description List of pickup orders */
            pickups: components["schemas"]["Order"][];
            /** @description List of delivery orders */
            deliveries: components["schemas"]["Order"][];
        };
        /** @description Result of a broadcast operation */
        BroadcastResult: {
            /** @description ID of the broadcast task */
            id: string;
            /** @description ID of the broadcast task */
            broadcast_task_id: string;
            /**
             * Format: date-time
             * @description Timestamp when the object was created
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /** @description Customer reference */
            customer: components["schemas"]["CustomerRef"];
            /** @description Whether the broadcast was successful */
            success: boolean;
            /** @description Result message */
            message: string;
            /** @description Error details if any */
            error?: Record<string, never> | null;
        };
        /** @description Bank information */
        Bank: {
            /**
             * Format: uuid
             * @description Unique identifier for the bank
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            BankId: string;
            /**
             * @description NSPK bank identifier
             * @example 100000000004
             */
            NspkBankId: string;
            /**
             * @description Name of the bank
             * @example Т-Банк
             */
            BankName: string;
            /**
             * Format: uri
             * @description URL to the bank's logo
             * @example https://qr.nspk.ru/proxyapp/logo/bank100000000004.png
             */
            BankLogo: string;
            /**
             * @description Order/priority of the bank
             * @example 1
             */
            BankOrder: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Delivery"][];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeliveryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Delivery ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["DeliveryOverview"];
                    };
                };
            };
            /** @description Delivery not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeliveryStats: {
        parameters: {
            query?: {
                /** @description Filter orders by status */
                status?: "PENDING" | "PAYMENT_IN_PROGRESS" | "PAYMENT_FAILED" | "PAID" | "RESOLVING" | "CONCILIATION_PAYMENT_IN_PROGRESS" | "CONCILIATED" | "CANCELED";
            };
            header?: never;
            path: {
                /** @description Delivery ID */
                id: string;
                /** @description Output format */
                format: "CSV";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with CSV file */
            200: {
                headers: {
                    /** @description Attachment filename */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Delivery not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOrderOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["OrderOverview"];
                    };
                };
            };
            /** @description Delivery not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPatch"];
            };
        };
        responses: {
            /** @description Order successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Order"];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateOrderPicking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order Picking ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPickingPatch"];
            };
        };
        responses: {
            /** @description Order picking successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["OrderPicking"];
                    };
                };
            };
            /** @description Order picking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    collectOrderPickingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order Picking ID */
                pickingId: string;
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item successfully collected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order picking or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startOrderPicking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order picking found or created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["OrderPicking"];
                    };
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    consolidateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order successfully resolved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order successfully cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g., order cannot be cancelled in current status) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getConciliationOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Order"];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPaymentsForOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Payment"][];
                    };
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createPaymentForOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Idempotency key to prevent duplicate payment creation
                     * @example unique-key-123
                     */
                    idempotency_key: string;
                };
            };
        };
        responses: {
            /** @description Payment created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Payment"];
                    };
                };
            };
            /** @description Order already has a payment in status 'SENT' or 'CONFIRMED' */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMessagesForCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["ConversationMessage"][];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sendMessageToCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The text message to send
                     * @example Hello, this is a test message
                     */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Message sent successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["ConversationMessage"];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getComments: {
        parameters: {
            query?: {
                /** @description Filter comments by entity ID */
                entity_id?: string;
                /** @description Filter comments by class/type */
                class?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Comment"][];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The comment text content
                     * @example This is a comment
                     */
                    text: string;
                    /**
                     * @description ID of the entity this comment belongs to
                     * @example order-456
                     */
                    entity_id: string;
                    /**
                     * @description The class/type of the comment
                     * @example NOTE
                     */
                    class: string;
                };
            };
        };
        responses: {
            /** @description Comment created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Comment"];
                    };
                };
            };
            /** @description Bad request (e.g., missing required fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createBroadcastTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The message to broadcast to customers
                     * @example Hello, this is a broadcast message
                     */
                    message: string;
                };
            };
        };
        responses: {
            /** @description Broadcast task created successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g., missing message) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    runBroadcastTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Broadcast task ID */
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Broadcast task executed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["BroadcastResult"][];
                    };
                };
            };
            /** @description Broadcast task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getItemsByCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category name */
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["ItemOverview"][];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
                /** @description Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["ItemOverview"];
                    };
                };
            };
            /** @description Customer or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCartItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with cart items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["CartItem"][];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addItemToCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCartItem"];
            };
        };
        responses: {
            /** @description Item successfully added to cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["CartItem"];
                    };
                };
            };
            /** @description Customer or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeItemFromCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveFromCartItem"];
            };
        };
        responses: {
            /** @description Item successfully removed from cart */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer or cart item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createOrderAndPaymentFromCart: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency key to prevent duplicate order creation */
                idempotency_key: string;
            };
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders created and payments initialized successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: {
                            orders?: components["schemas"]["Order"][];
                            payments?: components["schemas"]["Payment"][];
                        };
                    };
                };
            };
            /** @description Bad request (e.g., cart is empty, invalid idempotency key) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict (e.g., duplicate request with same idempotency key) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: {
                            /**
                             * @description URL for payment processing
                             * @example https://securepay.tinkoff.ru/payment/init?PaymentId=123456
                             */
                            paymentUrl?: string;
                        };
                    };
                };
            };
            /** @description Bad request (e.g., customer already has an active subscription) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerOrders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with customer orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["OrderOverview"][];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createOrderFromCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order successfully created from cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Order"];
                    };
                };
            };
            /** @description Customer not found or cart is empty */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with customer overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["CustomerOverview"];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerBanks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Customer ID */
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with list of banks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["Bank"][];
                    };
                };
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Unauthorized (user not authenticated) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signupUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Bad request (e.g., email already exists, invalid input) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description User authenticated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Bad request (e.g., missing fields, invalid credentials) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized (invalid credentials) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeliveryAgentOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Delivery agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example OK */
                        code?: string;
                        data?: components["schemas"]["DeliveryAgentOverview"];
                    };
                };
            };
            /** @description Delivery agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    markOrderAsDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order successfully marked as delivered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request (e.g., order cannot be delivered in current status) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
