/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/private/customers/{customerId}/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get messages from a customer's latest chat */
        get: operations["getLatestCustomerChatMessages"];
        put?: never;
        /**
         * Create a message in a customer's chat
         * @description Create a new message in the given customer's chat and return it.
         */
        post: operations["createCustomerChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Customer: {
            /**
             * @description Customer's first name
             * @example Антон
             */
            first_name: string;
            /**
             * @description Customer's first name
             * @example Антон
             */
            last_name: string;
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * @description Unique identifier in the system of origin (e.g., Telegram or VK)
             * @example 1019705782
             */
            external_id: string;
            /**
             * @description Whether the customer is a bot
             * @example null
             */
            is_bot?: boolean | null;
            /**
             * @description Customer's language code
             * @example ru
             */
            language_code?: string;
            /**
             * @description Customer's username
             * @example getting_drunk
             */
            username?: string;
            /**
             * Format: date-time
             * @description When customer was created
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When customer was last seen
             * @example 2025-11-23T00:00:00.000Z
             */
            last_seen_at: string;
            /**
             * @description Customer origin
             * @example TELEGRAM
             * @enum {enum}
             */
            origin: "TELEGRAM" | "VK";
        };
        Subscription: {
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * Format: date-time
             * @description When subscription was created
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When subscription was canceled
             * @example 2025-11-23T00:00:00.000Z
             */
            canceled_at?: string;
            /**
             * Format: date-time
             * @description When to charge next payment
             * @example 2025-11-23T00:00:00.000Z
             */
            next_payment_at: string;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "CANCELED" | "CANCELED_PAYMENT_OVERDUE";
            /**
             * Format: float
             * @description Cost of the subscription
             * @example 609
             */
            fee: number;
        };
        CustomerOverview: {
            balance: components["schemas"]["CustomerBalance"];
            stats?: components["schemas"]["CustomerStats"];
            subscription?: components["schemas"]["Subscription"];
            /**
             * @description Whether the customer is a member (has an active subscription)
             * @example true
             */
            is_member?: boolean;
        } & components["schemas"]["Customer"];
        OrderPickingPatch: {
            /** @description Items to update in this order picking */
            items: components["schemas"]["PickingItem"][];
        };
        OrderPatch: {
            /**
             * @description Name of the customer
             * @example Updated Order Name
             */
            name?: string;
            /**
             * @description Address of shipping
             * @example Oak str 1.
             */
            shipping_address?: string;
        };
        OrderPicking: {
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            id: string;
            delivery: components["schemas"]["DeliveryRef"];
            /** @description Items in this order picking */
            items: components["schemas"]["PickingItem"][];
            owner: components["schemas"]["OwnerRef"];
            /**
             * @description Order picking status
             * @example PENDING
             */
            status: string;
            /**
             * Format: float
             * @description Total value
             * @example 0
             */
            total: number;
            /**
             * @description Order picking type
             * @example ORIGINAL
             */
            type: string;
        };
        CartItem: {
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * Format: float
             * @description Fraction value
             * @example 0.42
             */
            fraction: number;
            /**
             * @description Item group
             * @example MOSCOW
             */
            group: string;
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            id: string;
            /**
             * @description Unique identifier for the cart item
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            item_id: string;
            /**
             * @description Item name
             * @example Горгонзола (Бразилия) Кусок 0.42 Кг
             */
            name: string;
            /**
             * Format: float
             * @description Price for the total quantity and fraction
             * @example 609
             */
            price: number;
            /**
             * Format: float
             * @description Non-member price for the total quantity and fraction
             * @example 609
             */
            non_member_price: number;
            /**
             * Format: float
             * @description Price for one unit
             * @example 609
             */
            price_for_unit: number;
            /**
             * Format: float
             * @description Non-member price for one unit
             * @example 609
             */
            non_member_price_for_unit: number;
            /**
             * @description Quantity
             * @example 1
             */
            quantity: number;
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at?: string;
        };
        PickingItem: {
            /** @enum {string} */
            status?: "PENDING" | "COLLECTED" | "CANCELED";
        } & components["schemas"]["CartItem"];
        ItemOverview: {
            /** @description Deliveries containing this item group */
            deliveries?: components["schemas"]["DeliveryRef"][];
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * @description Item description
             * @example мясо
             */
            description: string;
            /**
             * @description Is item sells by weight
             * @example true
             */
            is_weighted: boolean;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.2
             */
            fraction: number;
            /**
             * Format: float
             * @description Fraction price out
             * @example 1439
             */
            fraction_price_out: number;
            /**
             * Format: float
             * @description Non-member fraction price out
             * @example 1439
             */
            non_member_fraction_price_out: number;
            /**
             * Format: float
             * @description Non-member unit price out
             * @example 1439
             */
            non_member_unit_price_out: number;
            /**
             * @description Item group
             * @example BALASHOV
             */
            group: string;
            /**
             * @description Unique identifier for the item
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            id: string;
            /**
             * @description Link to item details
             * @example https://t.me/posebestoimosti_saratov/214
             */
            link: string;
            /**
             * @description Item name
             * @example Телятина Филе (Тендер Лоин)
             */
            name: string;
            /**
             * Format: float
             * @description Price out
             * @example 1199
             */
            price_out: number;
            /**
             * @description Unit of measurement
             * @example Кг
             */
            unit: string;
            /**
             * @description Unit description
             * @example Отруб
             */
            unit_description: string;
            /** @description Statistics for the item including likes and share enters */
            stats?: components["schemas"]["ItemStats"];
        };
        OwnerRef: {
            /**
             * @description Owner ID
             * @example 270053857
             */
            id: string;
        };
        DeliveryRef: {
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            delivery_end: string;
            /**
             * Format: date-time
             * @description Delivery start date and time
             * @example 2025-11-21T00:00:00.000Z
             */
            delivery_start: string;
            /**
             * @description Unique identifier for the order picking
             * @example ef4d5632-ba34-4488-97a5-b9b7af299535
             */
            id: string;
        };
        CustomerRef: {
            /**
             * @description Customer ID
             * @example 1019705782
             */
            id: string;
            /**
             * @description Customer's username
             * @example getting_drunk
             */
            username?: string;
            /**
             * @description Customer's first name
             * @example Антон
             */
            first_name?: string;
            /**
             * @description Customer's last name
             * @example Антон
             */
            last_name?: string;
        };
        Item: {
            /**
             * @description Item category
             * @example MEAT
             */
            category: string;
            /**
             * @description Item description
             * @example мясо
             */
            description: string;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.2
             */
            fraction: number;
            /**
             * Format: float
             * @description Fraction price out
             * @example 1439
             */
            fraction_price_out: number;
            /**
             * Format: float
             * @description Non-member fraction price out
             * @example 1439
             */
            non_member_fraction_price_out: number;
            /**
             * Format: float
             * @description Non-member unit price out
             * @example 1439
             */
            non_member_unit_price_out: number;
            /**
             * @description Item group
             * @example BALASHOV
             */
            group: string;
            /**
             * @description Unique identifier for the item
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            id: string;
            /**
             * @description Link to item details
             * @example https://t.me/posebestoimosti_saratov/214
             */
            link: string;
            /**
             * @description Item name
             * @example Телятина Филе (Тендер Лоин)
             */
            name: string;
            /**
             * Format: float
             * @description Price in
             * @example 1000
             */
            price_in: number;
            /**
             * Format: float
             * @description Price out
             * @example 1199
             */
            price_out: number;
            /**
             * @description Row number
             * @example 11
             */
            row_number: number;
            /**
             * @description Item status
             * @example ACTIVE
             */
            status: string;
            /**
             * @description Unit of measurement
             * @example Кг
             */
            unit: string;
            /**
             * @description Unit description
             * @example Отруб
             */
            unit_description: string;
            /**
             * @description Is item sells by weight
             * @example true
             */
            is_weighted: boolean;
        };
        Stats: {
            /**
             * Format: float
             * @description Total value
             * @example 4498
             */
            total: number;
            /**
             * Format: float
             * @description Fraction value
             * @example 1.8
             */
            fraction: number;
            /**
             * Format: integer
             * @description Quantity of items
             * @example 1
             */
            quantity: number;
            /**
             * @description Name of the stats item
             * @example Сёмга филе Филе на коже 1.8 Кг
             */
            name: string;
            /**
             * @description Category of the stats item
             * @example Сёмга филе Филе на коже 1.8 Кг
             */
            category: string;
        };
        ItemStats: {
            /**
             * @description Number of likes for the item
             * @example 42
             */
            number_of_likes?: number;
            /**
             * @description Number of share enters for the item
             * @example 15
             */
            number_of_share_enters?: number;
        };
        DeliveryOverviewItemStats: {
            orders?: components["schemas"]["Order"][];
        } & components["schemas"]["Stats"];
        Delivery: {
            /**
             * @description Unique identifier for the delivery
             * @example delivery-123
             */
            id: string;
            /**
             * @description Delivery number
             * @example 1001
             */
            number: number;
            /**
             * @description Description of the delivery
             * @example Weekly grocery delivery
             */
            description: string;
            /**
             * @description Current status of the delivery
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "IN_TRANSIT" | "IN_TRANSIT_BACK" | "FULFILLED";
            /**
             * Format: date-time
             * @description Deadline for placing orders
             * @example 2025-01-15T23:59:59Z
             */
            order_deadline: string;
            /**
             * Format: date-time
             * @description Start date and time of delivery
             * @example 2025-01-16T08:00:00Z
             */
            delivery_start: string;
            /**
             * Format: date-time
             * @description End date and time of delivery
             * @example 2025-01-16T18:00:00Z
             */
            delivery_end: string;
            /**
             * @description Delivery group identifier
             * @example group-a
             */
            group: string;
            /** @description List of orders in this delivery */
            orders: components["schemas"]["Order"][];
            owner?: components["schemas"]["OwnerRef"];
        };
        DeliveryOverview: {
            /** @description List of active orders in this delivery. All orders which are not CANCELED */
            activeOrders?: components["schemas"]["Order"][];
            /** @description List of active orders in this delivery. All orders which are not CANCELED */
            cancelledOrders?: components["schemas"]["Order"][];
            /** @description List of all CANCELED orders in this delivery */
            removedOrders?: components["schemas"]["Order"][];
            /** @description Statistics for the delivery */
            stats?: components["schemas"]["DeliveryOverviewItemStats"][];
        } & components["schemas"]["Delivery"];
        Order: {
            /**
             * @description Unique identifier for the order
             * @example order-456
             */
            id: string;
            /**
             * @description Original order this order is consolidated with
             * @example order-45611
             */
            reconciliated_order_id?: string;
            /**
             * @description Name of the customer
             * @example Order 1
             */
            name?: string;
            /**
             * @description Address
             * @example Str 1, city
             */
            shipping_address?: string;
            delivery?: components["schemas"]["DeliveryRef"];
            /** @description Items in this order */
            items: components["schemas"]["CartItem"][];
            /** @enum {string} */
            status: "PENDING" | "PAYMENT_IN_PROGRESS" | "PAYMENT_FAILED" | "PAID" | "RESOLVING" | "CONCILIATION_PAYMENT_IN_PROGRESS" | "CONSOLIDATION_SUCCESSFUL" | "CONCILIATED" | "CANCELED" | "DELIVERED";
            /**
             * @description Current status of the order
             * @example CONCILIATION
             * @enum {string}
             */
            type: "CONCILIATION" | "ORIGINAL";
            owner: components["schemas"]["OwnerRef"];
            /**
             * @description Number of items in the order
             * @example 5
             */
            number_of_items?: number;
            /**
             * Format: float
             * @description Total value of the order
             * @example 150.75
             */
            total: number;
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Delivery end date and time
             * @example 2025-11-23T00:00:00.000Z
             */
            updated_at: string;
        };
        OrderOverview: {
            picking?: components["schemas"]["OrderPicking"];
            customer: components["schemas"]["CustomerOverview"];
            comments?: components["schemas"]["Comment"];
            payment?: components["schemas"]["Payment"];
        } & components["schemas"]["Order"];
        User: {
            /**
             * @description Unique identifier for the user
             * @example user-123
             */
            id: string;
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * Format: hash
             * @description hashed password
             * @example sdfee335gsdfwDEfggh
             */
            password?: string;
            /**
             * Format: jwt
             * @description jwt token
             * @example sdfee335gsdfwDEfggh
             */
            token?: string;
            /** @description User roles */
            roles: ("AGENT" | "ADMIN")[];
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-01-01T00:00:00Z
             */
            created_at?: string;
            /** @description User label information */
            label?: {
                /**
                 * @description Label expiration timestamp
                 * @example 1735689600
                 */
                expiration?: number;
            };
        };
        Error: {
            error: {
                /**
                 * @description Error code
                 * @example NOT_FOUND
                 */
                code: string;
                /**
                 * @description Error message
                 * @example Delivery not found
                 */
                message: string;
            };
        };
        /** @description A message sent in a conversation */
        ConversationMessage: {
            /** @description Unique identifier for the message */
            readonly id: string;
            /** @description Unique identifier a thread those messages belongs to */
            thread_id: string;
            /**
             * @description The provider used to send the message
             * @enum {string}
             */
            provider: "TELEGRAM" | "OTHER";
            /**
             * @description The provider used to send the message
             * @enum {string}
             */
            role: "CUSTOMER" | "ADMIN";
            /** @description The chat ID where the message was sent */
            recipient_id?: string;
            /** @description The content of the message */
            text: string;
            /**
             * Format: date-time
             * @description Timestamp when the message was created
             */
            created_at: string;
        };
        Payment: {
            /**
             * @description URL for payment processing
             * @example https://securepay.tinkoff.ru/payment/init
             */
            payment_url: string;
            /**
             * @description Error code from payment provider
             * @example 0
             */
            error_code?: string | null;
            /**
             * @description Message from payment provider
             * @example 0
             */
            message?: string | null;
            /** @enum {string} */
            status: "SENT" | "CONFIRMED" | "FAILED" | "TIMED_OUT" | "CANCELED" | "REJECTED";
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            /**
             * @description Payment ID from external payment provider
             * @example 123456
             */
            external_id: string;
            /**
             * @description Terminal key from payment provider
             * @example TinkoffBankTest
             */
            terminal_key: string;
            /**
             * @description Order ID associated with the payment
             * @example order-456
             */
            order_id: string;
            /**
             * @description Payment amount in minor units (kopecks)
             * @example 15000
             */
            amount: number;
            /**
             * @description Payment amount in minor units (kopecks)
             * @example 15000
             */
            total: number;
            /**
             * @description Whether the payment was successful
             * @example true
             */
            success: boolean;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            updated_at: string;
            /**
             * Format: date-time
             * @description Payment creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            confirmed_at?: string;
        };
        CustomerBalance: {
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: float
             * @description Customer balance amount
             * @example 150.75
             */
            value: number;
            /**
             * Format: date-time
             * @description Balance creation timestamp
             * @example 2025-01-10T14:30:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Balance last update timestamp
             * @example 2025-01-10T14:30:00Z
             */
            updated_at?: string;
        };
        CustomerAccounting: {
            /**
             * @description Internal payment ID
             * @example payment-123456
             */
            id: string;
            /**
             * @description Id at bank to charge recursive payments
             * @example some-id-here
             */
            rebill_id: string;
        };
        CustomerStats: {
            /**
             * @description Unique identifier for the customer
             * @example 1019705782
             */
            id: string;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_orders: number;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_active_orders: number;
            /**
             * @description Total number of orders for the customer
             * @example 10
             */
            number_of_free_orders: number;
            /**
             * @description Number of canceled orders for the customer
             * @example 2
             */
            number_of_canceled_orders: number;
            /**
             * @description Number of fulfilled orders for the customer
             * @example 7
             */
            number_of_fulfilled_orders: number;
            /**
             * @description Number of paid subscription months for the customer
             * @example 3
             */
            number_of_paid_months: number;
            /**
             * Format: float
             * @description Total amount paid by the customer
             * @example 4500.75
             */
            paid_in_total: number;
        };
        SignupRequest: {
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User's password (min 6 characters)
             * @example password123
             */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User's email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User's password
             * @example password123
             */
            password: string;
        };
        AddToCartItem: {
            /**
             * @description Item ID to add to cart
             * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
             */
            itemId: string;
        };
        RemoveFromCartItem: {
            /**
             * @description Cart item ID to remove from cart
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            cartItemId?: string;
            /**
             * @description item ID to remove from cart. All the cart items of this item will be removed
             * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
             */
            itemId?: string;
        };
        Comment: {
            /**
             * @description The comment text content
             * @example This is a comment
             */
            text: string;
            /** @description The owner of the comment */
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: date-time
             * @description Timestamp when the comment was created
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /**
             * @description Unique identifier for the comment
             * @example comment-123456
             */
            id: string;
            /**
             * @description ID of the entity this comment belongs to
             * @example order-456
             */
            entity_id: string;
            /**
             * @description The class/type of the comment
             * @example NOTE
             */
            class: string;
        };
        DeliveryAgentOverview: {
            /**
             * @description Unique identifier for the delivery agent
             * @example agent-123
             */
            id: string;
            /**
             * @description Name of the delivery agent
             * @example John Doe
             */
            name: string;
            /** @description List of pickup orders */
            pickups: components["schemas"]["Order"][];
            /** @description List of delivery orders */
            deliveries: components["schemas"]["Order"][];
        };
        /** @description Result of a broadcast operation */
        BroadcastResult: {
            /** @description ID of the broadcast task */
            id: string;
            /** @description ID of the broadcast task */
            broadcast_task_id: string;
            /**
             * Format: date-time
             * @description Timestamp when the object was created
             * @example 2025-01-10T14:30:00Z
             */
            created_at: string;
            /** @description Customer reference */
            customer: components["schemas"]["CustomerRef"];
            /** @description Whether the broadcast was successful */
            success: boolean;
            /** @description Result message */
            message: string;
            /** @description Error details if any */
            error?: Record<string, never> | null;
        };
        /** @description A message in an AI chat. */
        ChatMessage: {
            /**
             * @description Unique identifier of the message.
             * @example msg_01J9Z7Y6X5W4V3U2T1S0
             */
            id: string;
            /**
             * @description Unique identifier of the chat to which the message belongs.
             * @example chat_01J9Z7Y6X5W4V3U2T1S0
             */
            chat_id: string;
            /**
             * @description Author of the message.
             * @example assistant
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * @description Text content of the message.
             * @example How can I help you today?
             */
            content: string;
            owner: components["schemas"]["OwnerRef"];
            /**
             * Format: date-time
             * @description Time the message was created.
             * @example 2026-09-12T14:30:00Z
             */
            created_at: string;
        };
        /** @description Filter for querying messages */
        MessageFilter: {
            /**
             * @description Filter messages by thread ID
             * @example thread-123
             */
            threadId?: string;
            /**
             * @description Filter messages by recipient
             * @example CUSTOMER
             */
            recipient?: string;
        };
        /** @description Масло из доступного списка продуктов, передаваемого агенту подбора */
        AvailableOil: {
            /**
             * @description Идентификатор продукта
             * @example oil_001
             */
            id: string;
            /**
             * @description Название масла
             * @example Mobil 1 ESP 5W-30
             */
            name: string;
            /**
             * @description Вязкость (SAE)
             * @example 5W-30
             */
            sae: string;
            /**
             * @description Список допусков API
             * @example [
             *       "SN"
             *     ]
             */
            api: string[];
            /**
             * @description Список допусков ACEA
             * @example [
             *       "C3"
             *     ]
             */
            acea: string[];
            /**
             * @description Список OEM-допусков производителя автомобиля
             * @example [
             *       "VW 507 00"
             *     ]
             */
            oem_approvals?: string[];
        };
        /**
         * @description Сообщение (AI message), передаваемое агенту подбора моторного масла.
         *     Содержит описание автомобиля пользователя и список доступных масел.
         */
        OilAgentMessage: {
            /**
             * @description Описание автомобиля пользователя
             * @example Volkswagen Passat 2019 2.0 TDI 150 hp
             */
            car: string;
            /** @description Список доступных масел, из которых агент выбирает подходящие */
            available_oils: components["schemas"]["AvailableOil"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLatestCustomerChatMessages: {
        parameters: {
            query?: {
                /** @description Return messages older than this message ID. */
                oldestMessage?: string;
            };
            header?: never;
            path: {
                /** @description Unique identifier of the customer. */
                customerId: string;
                /** @description Unique identifier of the chat. */
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages from the customer's latest chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Customer or chat not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCustomerChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the customer. */
                customerId: string;
                /** @description Unique identifier of the chat. */
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessage"];
            };
        };
        responses: {
            /** @description The created message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
            /** @description Customer or chat not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
