export const COLLECTIONS = {
    CUSTOMERS: 'CUSTOMERS',
    USERS: 'USERS',
    DELIVERIES: 'DELIVERIES',
    ORDERS: 'ORDERS',
};




export const HTTP_ERRORS = {
    UNAUTHORIZED : 'UNAUTHORIZED',
    NOT_FOUND : 'NOT_FOUND',
};
