export const COLLECTIONS = {
    CUSTOMERS: 'CUSTOMERS',
    USERS: 'USERS',
    DELIVERIES: 'DELIVERIES',
    ORDERS: 'ORDERS',
    PICKINGS: 'PICKINGS',
    ITEMS: 'ITEMS',
    CART_ITEMS: 'CART_ITEMS',
};




export const HTTP_ERRORS = {
    UNAUTHORIZED : 'UNAUTHORIZED',
    NOT_FOUND : 'NOT_FOUND',
};
