export const COLLECTIONS = {
    CUSTOMERS: 'CUSTOMERS',
    USERS: 'USERS',
    DELIVERIES: 'DELIVERIES',
    ORDERS: 'ORDERS',
    PICKINGS: 'PICKINGS',
    ITEMS: 'ITEMS',
    CART_ITEMS: 'CART_ITEMS',
    OUTBOX_EVENTS: 'OUTBOX_EVENTS',
    IDEMPOTENT_REQUESTS: 'IDEMPOTENT_REQUESTS',
    PAYMENTS: 'PAYMENTS',
    CONVERSATION_MESSAGES: 'CONVERSATION_MESSAGES',
};
export const EVENTS = {
    ORDER_CONCILIATED: 'ORDER_CONCILIATED',
    ORDER_RESOLVED: 'ORDER_RESOLVED',
    ORDER_PAYMENT_CREATED: 'ORDER_PAYMENT_CREATED',
    BALANCE_CHANGE: 'BALANCE_CHANGE',

};




export const HTTP_ERRORS = {
    UNAUTHORIZED : 'UNAUTHORIZED',
    NOT_FOUND : 'NOT_FOUND',
};
