import {ConversationMessage, Customer} from "../models";
import ConversationMessageService from "./ConversationMessageService";
import {Firestore} from "firebase-admin/firestore";
import TelegramService from "./TelegramService";


export type MessagingContext = {
  format?: "Markdown" | "HTML" | "Plaintext",
  thread_id: string,
}

class MessagingService {
  conversationMessageService;

  constructor(db: Firestore) {
    this.conversationMessageService = new ConversationMessageService(db);
  }

  async sendMessage(receiver: Customer, text: string, context: MessagingContext): Promise<ConversationMessage | undefined> {
    if (receiver.origin !== "TELEGRAM") throw Error("Only telegram messaging is supported for. moment");

    const telegramService = new TelegramService();

    await telegramService.sendMessage(receiver.external_id, text, receiver.id, context.format);

    const message: ConversationMessage = {
      id: "", // will be generated by Firestore
      thread_id: context.thread_id,
      provider: receiver.origin,
      recipient_id: `${receiver.id}`, // rework all ids to string after NY delivery
      text,
      role: "ADMIN",
      created_at: new Date(),
    };

    return this.conversationMessageService.add(message);
  }
}

export default MessagingService;
