/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin/deliveries": {
    /**
     * Get all deliveries
     * @description Retrieve a list of all deliveries
     */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Delivery"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/deliveries/{id}": {
    /**
     * Get delivery by ID
     * @description Retrieve a specific delivery by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Delivery ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Delivery"];
            };
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Stats: {
      /**
       * Format: float
       * @description Total value
       * @example 4498
       */
      total: number;
      /**
       * Format: float
       * @description Fraction value
       * @example 1.8
       */
      fraction: number;
      /**
       * @description Name of the stats item
       * @example Сёмга филе Филе на коже 1.8 Кг
       */
      name: string;
    };
    DeliveryOverview: {
      /**
       * @description Unique identifier for the delivery
       * @example delivery-123
       */
      id: string;
      /**
       * @description Delivery number
       * @example 1001
       */
      number: number;
      /**
       * @description Description of the delivery
       * @example Weekly grocery delivery
       */
      description: string;
      /**
       * @description Current status of the delivery
       * @example PENDING
       * @enum {string}
       */
      status: "PENDING" | "IN_TRANSIT" | "IN_TRANSIT_BACK" | "FULFILLED";
      /**
       * Format: date-time
       * @description Deadline for placing orders
       * @example 2025-01-15T23:59:59Z
       */
      order_deadline: string;
      /**
       * Format: date-time
       * @description Start date and time of delivery
       * @example 2025-01-16T08:00:00Z
       */
      delivery_start: string;
      /**
       * Format: date-time
       * @description End date and time of delivery
       * @example 2025-01-16T18:00:00Z
       */
      delivery_end: string;
      /**
       * @description Delivery group identifier
       * @example group-a
       */
      group: string;
      /** @description List of orders in this delivery */
      orders: components["schemas"]["Order"][];
      /** @description Statistics for the delivery */
      stats?: components["schemas"]["Stats"][];
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-01T00:00:00Z
       */
      createdAt?: string;
      /** @description Owner information */
      owner?: {
        /**
         * @description Owner ID
         * @example user-123
         */
        id?: string;
      };
    };
    Order: {
      /**
       * @description Unique identifier for the order
       * @example order-456
       */
      id: string;
      /**
       * @description Name of the customer
       * @example John Doe
       */
      customerName: string;
      /**
       * Format: date-time
       * @description Date when the order was placed
       * @example 2025-01-10T14:30:00Z
       */
      orderDate: string;
      /**
       * @description Current status of the order
       * @example PAID
       * @enum {string}
       */
      status: "PENDING" | "PAID" | "CONSOLIDATED";
      /** @description Owner information */
      owner: {
        /**
         * @description Owner ID
         * @example user-123
         */
        id?: string;
      };
      /**
       * @description Number of items in the order
       * @example 5
       */
      numberOfItems: number;
      /**
       * Format: float
       * @description Total value of the order
       * @example 150.75
       */
      total?: number;
    };
    User: {
      /**
       * @description Unique identifier for the user
       * @example user-123
       */
      id: string;
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User roles
       * @example [
       *   "admin",
       *   "user"
       * ]
       */
      roles: string[];
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-01T00:00:00Z
       */
      createdAt?: string;
      /** @description User label information */
      label?: {
        /**
         * @description Label expiration timestamp
         * @example 1735689600
         */
        expiration?: number;
      };
    };
    Error: {
      error: {
        /**
         * @description Error code
         * @example NOT_FOUND
         */
        code: string;
        /**
         * @description Error message
         * @example Delivery not found
         */
        message: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
