/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  "/admin/deliveries": {
    /**
     * Get all deliveries
     * @description Retrieve a list of all deliveries
     */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Delivery"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/deliveries/{id}": {
    /**
     * Get delivery by ID
     * @description Retrieve a specific delivery by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Delivery ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["DeliveryOverview"];
            };
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}": {
    /**
     * Get order overview by ID
     * @description Retrieve a specific delivery by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderOverview"];
            };
          };
        };
        /** @description Delivery not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/order-pickings/{id}": {
    /**
     * Update order picking items
     * @description Update the items in an order picking
     */
    patch: {
      parameters: {
        path: {
          /** @description Order Picking ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["OrderPickingPatch"];
        };
      };
      responses: {
        /** @description Order picking successfully updated */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderPicking"];
            };
          };
        };
        /** @description Order picking not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/order-pickings/{pickingId}/items/{itemId}/collect": {
    /**
     * Collect an item in an order picking
     * @description Mark an item in an order picking as collected.
     */
    post: {
      parameters: {
        path: {
          /** @description Order Picking ID */
          pickingId: string;
          /** @description Item ID */
          itemId: string;
        };
      };
      responses: {
        /** @description Item successfully collected */
        204: {
          content: never;
        };
        /** @description Order picking or item not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}/order-picking": {
    /**
     * Start order picking process
     * @description Check if order picking exists, return existing one or create new from order
     */
    post: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Order picking found or created successfully */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["OrderPicking"];
            };
          };
        };
        /** @description Order not found */
        404: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/admin/orders/{id}/consolidate": {
    /**
     * Resolve an order
     * @description Marks an order as resolved.
     */
    post: {
      parameters: {
        path: {
          /** @description Order ID */
          id: string;
        };
      };
      responses: {
        /** @description Order successfully resolved */
        204: {
          content: never;
        };
      };
    };
  };
  "/private/items/category/{category}": {
    /**
     * Get items by category
     * @description Retrieve a list of items for a specific category
     */
    get: {
      parameters: {
        path: {
          /** @description Category name */
          category: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Item"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/private/customers/{customerId}/cart/items/{itemId}": {
    /**
     * Add item to cart
     * @description Add an item to a customer's cart
     */
    post: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: number;
          /** @description Item ID */
          itemId: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Item"][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/private/customers/{customerId}/orders": {
    /**
     * Create order from cart
     * @description Create a new order from a customer's cart
     */
    post: {
      parameters: {
        path: {
          /** @description Customer ID */
          customerId: number;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": {
              /** @example OK */
              code?: string;
              data?: components["schemas"]["Order"];
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Customer: {
      /**
       * @description Customer's first name
       * @example Антон
       */
      first_name: string;
      /**
       * @description Unique identifier for the customer
       * @example 1019705782
       */
      id: number;
      /**
       * @description Whether the customer is a bot
       * @example null
       */
      is_bot?: boolean | null;
      /**
       * @description Customer's language code
       * @example ru
       */
      language_code: string;
      /**
       * @description Customer's username
       * @example getting_drunk
       */
      username: string;
    };
    OrderPickingPatch: {
      /** @description Items to update in this order picking */
      items: components["schemas"]["PickingItem"][];
    };
    OrderPicking: {
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      id: string;
      delivery: components["schemas"]["DeliveryRef"];
      /** @description Items in this order picking */
      items: components["schemas"]["PickingItem"][];
      owner: components["schemas"]["OwnerRef"];
      /**
       * @description Order picking status
       * @example PENDING
       */
      status: string;
      /**
       * Format: float
       * @description Total value
       * @example 0
       */
      total: number;
      /**
       * @description Order picking type
       * @example ORIGINAL
       */
      type: string;
    };
    CartItem: {
      /**
       * Format: float
       * @description Fraction value
       * @example 0.42
       */
      fraction: number;
      /**
       * @description Item group
       * @example MOSCOW
       */
      group: string;
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      id: string;
      /**
       * @description Unique identifier for the cart item
       * @example db13bdf1-cd12-4650-82be-f55af1e79bf7
       */
      item_id: string;
      /**
       * @description Item name
       * @example Горгонзола (Бразилия) Кусок 0.42 Кг
       */
      name: string;
      /**
       * Format: float
       * @description Price for the total quantity and fraction
       * @example 609
       */
      price: number;
      /**
       * Format: float
       * @description Price for one unit
       * @example 609
       */
      price_for_unit: number;
      /**
       * @description Quantity
       * @example 1
       */
      quantity: number;
      owner: components["schemas"]["OwnerRef"];
    };
    PickingItem: ({
      /** @enum {unknown} */
      status?: "PENDING" | "COLLECTED" | "CANCELLED";
    }) & components["schemas"]["OrderItem"];
    OwnerRef: {
      /**
       * @description Owner ID
       * @example 270053857
       */
      id: number;
    };
    DeliveryRef: {
      /**
       * Format: date-time
       * @description Delivery end date and time
       * @example 2025-11-23T00:00:00.000Z
       */
      delivery_end: string;
      /**
       * Format: date-time
       * @description Delivery start date and time
       * @example 2025-11-21T00:00:00.000Z
       */
      delivery_start: string;
      /**
       * @description Unique identifier for the order picking
       * @example ef4d5632-ba34-4488-97a5-b9b7af299535
       */
      id: string;
    };
    Item: {
      /**
       * @description Item category
       * @example MEAT
       */
      category: string;
      /**
       * @description Item description
       * @example мясо
       */
      description: string;
      /**
       * Format: float
       * @description Fraction value
       * @example 1.2
       */
      fraction: number;
      /**
       * Format: float
       * @description Fraction price out
       * @example 1439
       */
      fraction_price_out: number;
      /**
       * @description Item group
       * @example BALASHOV
       */
      group: string;
      /**
       * @description Unique identifier for the item
       * @example 06088197-f7ef-4bf2-8b3f-2f4a05c6c104
       */
      id: string;
      /**
       * @description Link to item details
       * @example https://t.me/posebestoimosti_saratov/214
       */
      link: string;
      /**
       * @description Item name
       * @example Телятина Филе (Тендер Лоин)
       */
      name: string;
      /**
       * Format: float
       * @description Price in
       * @example 1000
       */
      price_in: number;
      /**
       * Format: float
       * @description Price out
       * @example 1199
       */
      price_out: number;
      /**
       * @description Row number
       * @example 11
       */
      row_number: number;
      /**
       * @description Item status
       * @example ACTIVE
       */
      status: string;
      /**
       * @description Unit of measurement
       * @example Кг
       */
      unit: string;
      /**
       * @description Unit description
       * @example Отруб
       */
      unti_description: string;
    };
    Stats: {
      /**
       * Format: float
       * @description Total value
       * @example 4498
       */
      total: number;
      /**
       * Format: float
       * @description Fraction value
       * @example 1.8
       */
      fraction: number;
      /**
       * @description Name of the stats item
       * @example Сёмга филе Филе на коже 1.8 Кг
       */
      name: string;
    };
    Delivery: {
      /**
       * @description Unique identifier for the delivery
       * @example delivery-123
       */
      id: string;
      /**
       * @description Delivery number
       * @example 1001
       */
      number: number;
      /**
       * @description Description of the delivery
       * @example Weekly grocery delivery
       */
      description: string;
      /**
       * @description Current status of the delivery
       * @example PENDING
       * @enum {string}
       */
      status: "PENDING" | "IN_TRANSIT" | "IN_TRANSIT_BACK" | "FULFILLED";
      /**
       * Format: date-time
       * @description Deadline for placing orders
       * @example 2025-01-15T23:59:59Z
       */
      order_deadline: string;
      /**
       * Format: date-time
       * @description Start date and time of delivery
       * @example 2025-01-16T08:00:00Z
       */
      delivery_start: string;
      /**
       * Format: date-time
       * @description End date and time of delivery
       * @example 2025-01-16T18:00:00Z
       */
      delivery_end: string;
      /**
       * @description Delivery group identifier
       * @example group-a
       */
      group: string;
      /** @description List of orders in this delivery */
      orders: components["schemas"]["Order"][];
      owner?: components["schemas"]["OwnerRef"];
    };
    DeliveryOverview: {
      /** @description Statistics for the delivery */
      stats?: components["schemas"]["Stats"][];
    } & components["schemas"]["Delivery"];
    Order: {
      /**
       * @description Unique identifier for the order
       * @example order-456
       */
      id: string;
      /**
       * @description Name of the customer
       * @example Order 1
       */
      name?: string;
      /**
       * Format: date-time
       * @description Date when the order was placed
       * @example 2025-01-10T14:30:00Z
       */
      orderDate: string;
      /** @description Items in this order */
      items: components["schemas"]["CartItem"][];
      /**
       * @description Current status of the order
       * @example PAID
       * @enum {string}
       */
      status: "PENDING" | "PAID" | "CONSOLIDATED";
      owner: components["schemas"]["OwnerRef"];
      /**
       * @description Number of items in the order
       * @example 5
       */
      numberOfItems: number;
      /**
       * Format: float
       * @description Total value of the order
       * @example 150.75
       */
      total?: number;
    };
    OrderOverview: WithRequired<{
      picking?: components["schemas"]["OrderPicking"];
      customer: components["schemas"]["Customer"];
    } & components["schemas"]["Order"], "customer">;
    User: {
      /**
       * @description Unique identifier for the user
       * @example user-123
       */
      id: string;
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * @description User roles
       * @example [
       *   "admin",
       *   "user"
       * ]
       */
      roles: string[];
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example 2025-01-01T00:00:00Z
       */
      createdAt?: string;
      /** @description User label information */
      label?: {
        /**
         * @description Label expiration timestamp
         * @example 1735689600
         */
        expiration?: number;
      };
    };
    Error: {
      error: {
        /**
         * @description Error code
         * @example NOT_FOUND
         */
        code: string;
        /**
         * @description Error message
         * @example Delivery not found
         */
        message: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
